---
abstract: 'Document psuedo-streaming for YAML::Tiny'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  File::Spec: 0.80
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: YAML::Tiny::Stream
name: YAML-Tiny-Stream
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  IO::File: 1.14
  YAML::Tiny: 1.40
  perl: 5.6.0
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/YAML-Tiny-Stream
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/YAML-Tiny-Stream
version: 0.01
